[package]
name = "rusterize"
description="A 3D renderer built from per-pixel access."
version = "0.3.4"
authors = ["Zane Sterling <sterling.zane@gmail.com>"]
license = "MIT"

[dependencies]

[dependencies.sdl2]
version = "0.29"
