[package]
name = "rusterize"
version = "0.1.0"
authors = ["Zane Sterling <sterling.zane@gmail.com>"]

[profile.release]
debug = true

[dependencies]

[dependencies.sdl2]
version = "0.29"
default_features = false
features = ["gfx"]
